### ISSUE TITLE
Caching and Storing Data

### ISSUE THREAD

**Issue by canaleal** [GeotabInternalDevelopment/GEOTAB-USARS-SVELTE-DEMO#19]
Right now, we are loading data from the APIs. 

We can cache the neighboorhoods data and the trees data using service works, local storage and session storage. 

Recommendations:
-The kingston neighbourhood data has not changed since 2016, we might be able to save the data a local json file instead.
-The trees data is quite large, we might be able to fetch the data using service works or saving the data in local storage. 
Note local storage can only hold **5MB** per browser. 

If we add all the trees, it will take up 1.5MB
https://opendatakingston.cityofkingston.ca/explore/dataset/trees-municipal/export/?disjunctive.owner&disjunctive.common_name&disjunctive.scientific_name&location=12,44.33757,-76.45197&basemap=72525b

**Comment by amir002001** [comment]
done
