### ISSUE TITLE
Add a limit to the Polygon search Area size

### ISSUE THREAD

**Issue by canaleal** [GeotabInternalDevelopment/GEOTAB-USARS-SVELTE-DEMO#22]
Because there is so much data in big query we cannot fetch all of the points without taking a massive hit to performance. There are a few ways to limit the number of data we're fetching, the easiest way to limit the size of the search polygon (The one that the user draws)

Adding the limiter:
-Open the SearchDetails.svelte file
-Inside the file there is a variable called areaNumber
-Using the areaNumber variable, add an if condition inside the div that says 'Area is too large to search'

Set the max area to 15000m^2.

**Comment by burhanf** [comment]
Adds a check and displays a message in the div that the polygon size should be less than 15KM^2
